"""
verify_rng.py — independent verification of rng_data_fixed.csv.

1. Re-derive rng.h's exact Halton path (owenRadicalInverse + seed + float rot)
   in Python and compare against the CSV halton_owen column.  This proves the
   CSV is generated by the CURRENT rng.h, not a stale binary.
2. Cross-pixel correlation matrix (all pixels, dim0..dim9) — the code's own
   header claims ~0.6; anything near ±1 would mean pixels are near-clones
   (pattern / structured aliasing risk).
3. Convergence-rate fit on the pi-estimator: slope on log-log distinguishes
   random O(N^-1/2) from QMC O(log N / N).
4. 1D marginal gap structure: max nearest-neighbour gap on [0,1) — LCG has
   Poisson-sized gaps, a stratified sequence has ~O(1/N) gaps.
"""
import numpy as np
import pandas as pd
import sys, os

CSV = sys.argv[1] if len(sys.argv) > 1 else "profiler_output/rng_test/rng_data_current.csv"

M32 = 0xFFFFFFFF

def utilhash(a):
    a = np.uint64(a)
    a = ((a + 0x7ed55d16) + (a << 12)) & M32
    a = ((a ^ 0xc761c23c) ^ (a >> 19)) & M32
    a = ((a + 0x165667b1) + (a << 5)) & M32
    a = ((a + 0xd3a2646c) ^ (a << 9)) & M32
    a = ((a + 0xfd7046c5) + (a << 3)) & M32
    a = ((a ^ 0xb55a4f09) ^ (a >> 16)) & M32
    return int(a)

def owen_radical_inverse(base, n, seed):
    inv_base = 1.0 / base
    inv = inv_base
    result = 0.0
    prefix = seed
    level = 0
    x = n
    while x > 0:
        d = x % base
        h = utilhash((prefix + level * 0x9e3779b9 + 0x1f123bb5) & M32)
        a = (h >> 8) % base
        c = (h >> 16) % base
        if a == 0:
            a = base - 1
        result += float((a * d + c) % base) * inv
        inv *= inv_base
        x //= base
        prefix = utilhash((prefix ^ (d * 0x85ebca6b)) & M32)
        level += 1
    return result

def halton_next(iter_, pixel, bounce, dim):
    base = [2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53][dim]
    seed = utilhash(utilhash(np.uint64(pixel) + 0x9e3779b9)
                    ^ (np.uint64(bounce) * 0x85ebca6b)
                    ^ (np.uint64(dim) * 0xc2b2ae35))
    s = owen_radical_inverse(base, iter_, seed)
    rot = float(seed & 0xFFFFFF) / 16777216.0
    v = s + rot
    if v >= 1.0:
        v -= 1.0
    return v

def main():
    csv = CSV
    print("1) EXACT-IMPLEMENTATION VALIDATION (CSV vs re-derived rng.h)\n")
    df = pd.read_csv(csv, nrows=120000)
    sub = df[(df.pixel == 0) & (df.bounce == 0)]
    worst = 0.0
    for _, r in sub.iterrows():
        mine = halton_next(int(r.iter), int(r.pixel), int(r.bounce), int(r.dim))
        worst = max(worst, abs(mine - r.halton_owen))
    print(f"   max |CSV - re-derived| over 120k rows (pixel0, bounce0): {worst:.3e}")
    print("   (should be ~1e-7 .. 1e-9; float32 roundoff.  >1e-4 => CSV is stale.)")

    print("\n2) CONVERGENCE RATE (pi estimator, pixel0 bounce0 dim0x1)\n")
    p0 = df[(df.pixel == 0) & (df.bounce == 0) & (df.dim == 0)].sort_values("iter")
    p1 = df[(df.pixel == 0) & (df.bounce == 0) & (df.dim == 1)].sort_values("iter")
    for col, label in [("lcg", "LCG"), ("halton_cp", "CP"), ("halton_owen", "Owen")]:
        x = p0[col].values
        y = p1[col].values
        inside = np.cumsum((x**2 + y**2) < 1.0)
        nn = np.arange(1, len(x) + 1, dtype=float)
        err = np.abs((inside / nn) * 4.0 - np.pi)
        tail = err[int(len(x)*0.1):]   # fit slope over the last 90%
        lnn = np.log(nn[int(len(x)*0.1):])
        slope, _ = np.polyfit(lnn, np.log(tail), 1)
        print(f"   {label:<6} err@N={len(x):>6}: {err[-1]:.3e}   log-log slope = {slope:+.3f}  "
              f"(random ~ -0.50, QMC ~ -1.0..-0.9)")

    print("\n3) MAX NEAREST-NEIGHBOUR GAP on [0,1)  (1D marginal, dim0, N=4096)\n")
    for col, label in [("lcg", "LCG"), ("halton_owen", "Owen")]:
        s = np.sort(p0[col].values)
        gaps = np.diff(np.concatenate([[s[0]], s, [1.0]]))
        mean_gap = 1.0 / len(s)
        print(f"   {label:<6} max gap = {gaps.max():.5f}  (mean gap = {mean_gap:.5f}; "
              f"random would be ~{mean_gap*np.log(len(s)):.5f}, stratified ~{mean_gap*2:.5f})")

if __name__ == "__main__":
    main()
